/**
 * 聊天皮肤系统 —— 预生成二次元背景图库。
 *
 * 皮肤 = 聊天窗口背景图 + 深色遮罩，只作用于聊天窗口；
 * 气泡色仍随角色走（characters.ts 的 theme），两者解耦。
 *
 * 性别约束：theme.gender 表示「画面人物性别 = 适用的伴侣性别」。
 * 可选皮肤池按当前伴侣的性别动态过滤（运行时从角色定义查 gender，
 * 见 resolve-gender.ts），不写死任何角色名单，新增角色自动适配。
 *
 * 背景图为预生成 DeepSeek 原创素材（public/backgrounds/deepseek/）；
 * 每张图单独声明亮度与移动/桌面裁切点。
 */

export interface ChatTheme {
  id: string;
  name: string;
  /**
   * 英文名（**诗意重命名**，用户 2026-10-03 选定）：与中文 `name` 并存，中文态逐字符不变。
   * 与中文原名意象对齐，不是描述性直译。
   */
  nameEn: string;
  /** 氛围一句话（选择面板副标题） */
  desc: string;
  /** 英文副标题；保留 `FQxx · ` / `MQxx · ` 前缀与 `·` 分隔符（前缀与 id 的编号逐字符对应）。 */
  descEn: string;
  /** 画面人物性别 = 适用伴侣性别 */
  gender: 'male' | 'female';
  /** 背景图路径 */
  image: string;
  /** 横屏专用图；手机仍使用原始竖版图 */
  desktopImage?: string;
  /** 选择面板缩略图；未提供时回退 image */
  thumbnail?: string;
  /** 遮罩基调色（渐变遮罩，保证气泡可读性） */
  scrim: string;
  /** 素材级滤镜 */
  brightness?: number;
  saturation?: number;
  /** object-position：窄屏侧重横向裁切，桌面宽屏侧重纵向裁切 */
  mobilePosition?: string;
  desktopPosition?: string;
}

/** 默认皮肤 id（无背景图，保持角色原有纯色氛围；DB 中存储为 NULL） */
export const DEFAULT_CHAT_THEME_ID = 'default';

export const CHAT_THEMES: ChatTheme[] = [
  /* ---------- 女性向（伴侣为女生时可选） ---------- */
  /* DeepSeek manifest 已接入条目：源 PNG 只读保留，运行时使用 WebP 衍生图。 */
  {
    id: 'deepseek-fq01',
    name: '鲸月栈桥',
    nameEn: 'Whale-Moon Pier',
    desc: '她在月夜海边安静等你',
    descEn: 'She waits quietly by the moonlit sea',
    gender: 'female',
    image: '/backgrounds/deepseek/fq01.webp',
    desktopImage: '/backgrounds/deepseek/desktop/fq01.jpg',
    thumbnail: '/backgrounds/deepseek/thumbnails/fq01.webp',
    scrim: '#09101e',
    brightness: 1,
    saturation: 1,
    mobilePosition: '62% 50%',
    desktopPosition: '50% 60%',
  },
  {
    id: 'deepseek-fq02',
    name: '星穹观测',
    nameEn: 'Dome of Stars',
    desc: '她在天文台穹顶下校准望远镜，仰望星河',
    descEn: 'Under the observatory dome she adjusts the telescope, gazing up at the galaxy',
    gender: 'female',
    image: '/backgrounds/deepseek/fq02.webp',
    desktopImage: '/backgrounds/deepseek/desktop/fq02.jpg',
    thumbnail: '/backgrounds/deepseek/thumbnails/fq02.webp',
    scrim: '#091225',
    brightness: 1,
    saturation: 1,
    mobilePosition: '68% 50%',
    desktopPosition: '50% 38%',
  },
  {
    id: 'deepseek-fq03',
    name: '雨窗咖啡',
    nameEn: 'Rain at the Café Window',
    desc: '雨夜暖灯下，她捧着热饮等你',
    descEn: 'Under a warm lamp on a rainy night, she holds a hot drink and waits for you',
    gender: 'female',
    image: '/backgrounds/deepseek/fq03.webp',
    desktopImage: '/backgrounds/deepseek/desktop/fq03.jpg',
    thumbnail: '/backgrounds/deepseek/thumbnails/fq03.webp',
    scrim: '#0a1122',
    brightness: 1,
    saturation: 1,
    mobilePosition: '38% 50%',
    desktopPosition: '50% 56%',
  },
  {
    id: 'deepseek-fq04',
    name: '月下花房',
    nameEn: 'Greenhouse Under the Moon',
    desc: '她在花房门边轻轻回眸',
    descEn: 'She glances back softly from the door of the greenhouse',
    gender: 'female',
    image: '/backgrounds/deepseek/fq04.webp',
    desktopImage: '/backgrounds/deepseek/desktop/fq04.jpg',
    thumbnail: '/backgrounds/deepseek/thumbnails/fq04.webp',
    scrim: '#091225',
    brightness: 1,
    saturation: 1,
    mobilePosition: '65% 50%',
    desktopPosition: '50% 54%',
  },
  {
    id: 'deepseek-fq05',
    name: '鲸月夜读',
    nameEn: 'Reading by Whale-Light',
    desc: '她抱着鲸鱼，在月色里翻开书页',
    descEn: 'Holding her whale, she turns a page in the moonlight',
    gender: 'female',
    image: '/backgrounds/deepseek/fq05.webp',
    desktopImage: '/backgrounds/deepseek/desktop/fq05.jpg',
    thumbnail: '/backgrounds/deepseek/thumbnails/fq05.webp',
    scrim: '#081124',
    brightness: 1,
    saturation: 1,
    mobilePosition: '38% 50%',
    desktopPosition: '50% 63%',
  },
  {
    id: 'deepseek-fq06',
    name: '花火听风',
    nameEn: 'Fireworks, Listening to the Wind',
    desc: '她坐在古城屋顶看烟火，折扇轻摇等你',
    descEn: 'On an old town rooftop she watches the fireworks, folding fan in hand, waiting for you',
    gender: 'female',
    image: '/backgrounds/deepseek/fq06.webp',
    desktopImage: '/backgrounds/deepseek/desktop/fq06.jpg',
    thumbnail: '/backgrounds/deepseek/thumbnails/fq06.webp',
    scrim: '#091124',
    brightness: 1,
    saturation: 1,
    mobilePosition: '52% 50%',
    desktopPosition: '50% 52%',
  },
  {
    id: 'deepseek-fq07',
    name: '星港灯塔',
    nameEn: 'Lighthouse in the Star Harbor',
    desc: '她在星空与灯塔之间陪你看海',
    descEn: 'Between the stars and the lighthouse, she watches the sea with you',
    gender: 'female',
    image: '/backgrounds/deepseek/fq07.webp',
    desktopImage: '/backgrounds/deepseek/desktop/fq07.jpg',
    thumbnail: '/backgrounds/deepseek/thumbnails/fq07.webp',
    scrim: '#071127',
    brightness: 1,
    saturation: 1,
    mobilePosition: '66% 50%',
    desktopPosition: '50% 62%',
  },
  {
    id: 'deepseek-fq08',
    name: '雪窗守候',
    nameEn: 'Keeping Watch at the Snow Window',
    desc: '雪落港湾，她在窗边陪你等灯亮',
    descEn: 'Snow falls on the harbor; she keeps you company at the window until the lights come on',
    gender: 'female',
    image: '/backgrounds/deepseek/fq08.webp',
    desktopImage: '/backgrounds/deepseek/desktop/fq08.jpg',
    thumbnail: '/backgrounds/deepseek/thumbnails/fq08.webp',
    scrim: '#081126',
    brightness: 1,
    saturation: 1,
    mobilePosition: '38% 50%',
    desktopPosition: '50% 57%',
  },
  {
    id: 'deepseek-fn01',
    name: '晨海露台',
    nameEn: 'Morning Sea Terrace',
    desc: '晨光越过海面，她在露台等你醒来',
    descEn: 'Morning light crosses the water, and she waits on the terrace for you to wake',
    gender: 'female',
    image: '/backgrounds/deepseek/fn01.webp',
    desktopImage: '/backgrounds/deepseek/desktop/fn01.jpg',
    thumbnail: '/backgrounds/deepseek/thumbnails/fn01.webp',
    scrim: '#0a1730',
    brightness: 1,
    saturation: 1,
    mobilePosition: '64% 50%',
    desktopPosition: '50% 50%',
  },
  {
    id: 'deepseek-fn02',
    name: '蓝庭回眸',
    nameEn: 'Glance in the Blue Courtyard',
    desc: '月光落在玫瑰庭院，她回头看你',
    descEn: 'Moonlight on the rose courtyard, and she turns to look at you',
    gender: 'female',
    image: '/backgrounds/deepseek/fn02.webp',
    desktopImage: '/backgrounds/deepseek/desktop/fn02.jpg',
    thumbnail: '/backgrounds/deepseek/thumbnails/fn02.webp',
    scrim: '#081126',
    brightness: 1,
    saturation: 1,
    mobilePosition: '64% 50%',
    desktopPosition: '50% 42%',
  },
  {
    id: 'deepseek-fn03',
    name: '雨窗暖灯',
    nameEn: 'Warm Lamp, Rainy Window',
    desc: '雨落窗外，她抱着鲸鱼望向你',
    descEn: 'Rain beyond the window; she holds her whale and looks your way',
    gender: 'female',
    image: '/backgrounds/deepseek/fn03.webp',
    desktopImage: '/backgrounds/deepseek/desktop/fn03.jpg',
    thumbnail: '/backgrounds/deepseek/thumbnails/fn03.webp',
    scrim: '#0a1020',
    brightness: 1,
    saturation: 1,
    mobilePosition: '62% 50%',
    desktopPosition: '50% 48%',
  },
  {
    id: 'deepseek-fn04',
    name: '雨窗茶语',
    nameEn: 'Tea Talk at the Rainy Window',
    desc: '雨夜咖啡馆里，她捧着热饮望向你',
    descEn: 'In the café on a rainy night, she holds a hot drink and looks your way',
    gender: 'female',
    image: '/backgrounds/deepseek/fn04.webp',
    desktopImage: '/backgrounds/deepseek/desktop/fn04.jpg',
    thumbnail: '/backgrounds/deepseek/thumbnails/fn04.webp',
    scrim: '#081124',
    brightness: 1,
    saturation: 1,
    mobilePosition: '38% 50%',
    desktopPosition: '50% 40%',
  },
  {
    id: 'deepseek-fn05',
    name: '深蓝书梯',
    nameEn: 'The Deep-Blue Book Stair',
    desc: '她坐在深夜书房，为你留着一盏灯',
    descEn: 'She sits in a late-night study, keeping one lamp lit for you',
    gender: 'female',
    image: '/backgrounds/deepseek/fn05.webp',
    desktopImage: '/backgrounds/deepseek/desktop/fn05.jpg',
    thumbnail: '/backgrounds/deepseek/thumbnails/fn05.webp',
    scrim: '#071023',
    brightness: 1,
    saturation: 1,
    mobilePosition: '64% 50%',
    desktopPosition: '50% 38%',
  },
  {
    id: 'deepseek-fn06',
    name: '蓝港长阶',
    nameEn: 'Long Steps of the Blue Harbor',
    desc: '蓝小时的港口长阶，她陪你看灯火',
    descEn: 'On the long harbor steps in the blue hour, she watches the lights with you',
    gender: 'female',
    image: '/backgrounds/deepseek/fn06.webp',
    desktopImage: '/backgrounds/deepseek/desktop/fn06.jpg',
    thumbnail: '/backgrounds/deepseek/thumbnails/fn06.webp',
    scrim: '#08152b',
    brightness: 1,
    saturation: 1,
    mobilePosition: '32% 50%',
    desktopPosition: '50% 32%',
  },
  {
    id: 'deepseek-fn07',
    name: '月夜阅室',
    nameEn: 'Reading Room, Moonlit',
    desc: '她在月夜阅读室里，为你翻开一页',
    descEn: 'In the moonlit reading room, she turns a page open for you',
    gender: 'female',
    image: '/backgrounds/deepseek/fn07.webp',
    desktopImage: '/backgrounds/deepseek/desktop/fn07.jpg',
    thumbnail: '/backgrounds/deepseek/thumbnails/fn07.webp',
    scrim: '#071124',
    brightness: 1,
    saturation: 1,
    mobilePosition: '38% 50%',
    desktopPosition: '50% 55%',
  },
  {
    id: 'deepseek-fn08',
    name: '花房拾光',
    nameEn: 'Gathering Light in the Flower Room',
    desc: '她在夜间花房里，替你拾起一束微光',
    descEn: 'In the nighttime flower room, she gathers a sliver of light for you',
    gender: 'female',
    image: '/backgrounds/deepseek/fn08.webp',
    desktopImage: '/backgrounds/deepseek/desktop/fn08.jpg',
    thumbnail: '/backgrounds/deepseek/thumbnails/fn08.webp',
    scrim: '#071126',
    brightness: 1,
    saturation: 1,
    mobilePosition: '62% 50%',
    desktopPosition: '50% 52%',
  },
  {
    id: 'deepseek-fn09',
    name: '屋顶来信',
    nameEn: 'A Letter on the Rooftop',
    desc: '她在旧城屋顶，拆开一封写给你的信',
    descEn: 'On the old town rooftop, she opens a letter written for you',
    gender: 'female',
    image: '/backgrounds/deepseek/fn09.webp',
    desktopImage: '/backgrounds/deepseek/desktop/fn09.jpg',
    thumbnail: '/backgrounds/deepseek/thumbnails/fn09.webp',
    scrim: '#081227',
    brightness: 1,
    saturation: 1,
    mobilePosition: '35% 50%',
    desktopPosition: '50% 55%',
  },
  {
    id: 'deepseek-fn10',
    name: '雪夜拱廊',
    nameEn: 'Arcade on a Snowy Night',
    desc: '雪落长廊，她在暖灯下等你经过',
    descEn: 'Snow on the long gallery; she waits under a warm lamp for you to pass',
    gender: 'female',
    image: '/backgrounds/deepseek/fn10.webp',
    desktopImage: '/backgrounds/deepseek/desktop/fn10.jpg',
    thumbnail: '/backgrounds/deepseek/thumbnails/fn10.webp',
    scrim: '#081226',
    brightness: 1,
    saturation: 1,
    mobilePosition: '35% 50%',
    desktopPosition: '50% 32%',
  },
  {
    id: 'deepseek-fn11',
    name: '暖灯花笺',
    nameEn: 'Flower Note Under a Warm Lamp',
    desc: '她在暖杏灯下，为你插好一枝花',
    descEn: 'Under the warm apricot lamp, she arranges a single stem for you',
    gender: 'female',
    image: '/backgrounds/deepseek/fn11.webp',
    desktopImage: '/backgrounds/deepseek/desktop/fn11.jpg',
    thumbnail: '/backgrounds/deepseek/thumbnails/fn11.webp',
    scrim: '#081023',
    brightness: 1,
    saturation: 1,
    mobilePosition: '67% 50%',
    desktopPosition: '50% 32%',
  },
  {
    id: 'deepseek-fn12',
    name: '星城露台',
    nameEn: 'Terrace Over the City of Stars',
    desc: '她倚着城市露台，陪你看灯火入夜',
    descEn: 'Leaning on a city terrace, she watches the lights settle into night with you',
    gender: 'female',
    image: '/backgrounds/deepseek/fn12.webp',
    desktopImage: '/backgrounds/deepseek/desktop/fn12.jpg',
    thumbnail: '/backgrounds/deepseek/thumbnails/fn12.webp',
    scrim: '#071126',
    brightness: 1,
    saturation: 1,
    mobilePosition: '35% 50%',
    desktopPosition: '50% 40%',
  },
  /* ---------- 男性向（伴侣为男生时可选） ---------- */
  {
    id: 'deepseek-mq01',
    name: '鲸月书房',
    nameEn: 'Whale-Moon Study',
    desc: '他在海边月色里翻开书页',
    descEn: 'He opens a book in the seaside moonlight',
    gender: 'male',
    image: '/backgrounds/deepseek/mq01.webp',
    desktopImage: '/backgrounds/deepseek/desktop/mq01.jpg',
    thumbnail: '/backgrounds/deepseek/thumbnails/mq01.webp',
    scrim: '#071126',
    brightness: 1,
    saturation: 1,
    mobilePosition: '38% 50%',
    desktopPosition: '50% 60%',
  },
  {
    id: 'deepseek-mq02',
    name: '雨窗夜读',
    nameEn: 'Night Reading by the Rain',
    desc: '雨夜窗边，他捧着鲸鱼书静静等你',
    descEn: 'At the rain-streaked window he waits quietly, his whale book in hand',
    gender: 'male',
    image: '/backgrounds/deepseek/mq02.webp',
    desktopImage: '/backgrounds/deepseek/desktop/mq02.jpg',
    thumbnail: '/backgrounds/deepseek/thumbnails/mq02.webp',
    scrim: '#071126',
    brightness: 1,
    saturation: 1,
    mobilePosition: '68% 50%',
    desktopPosition: '50% 62%',
  },
  {
    id: 'deepseek-mq03',
    name: '灯塔夜港',
    nameEn: 'Lighthouse Over the Night Harbor',
    desc: '他在港湾灯火边，把小鲸鱼带给你',
    descEn: 'By the harbor lights, he brings you a little whale',
    gender: 'male',
    image: '/backgrounds/deepseek/mq03.webp',
    desktopImage: '/backgrounds/deepseek/desktop/mq03.jpg',
    thumbnail: '/backgrounds/deepseek/thumbnails/mq03.webp',
    scrim: '#071126',
    brightness: 1,
    saturation: 1,
    mobilePosition: '34% 50%',
    desktopPosition: '50% 62%',
  },
  {
    id: 'deepseek-mq04',
    name: '海岸暖饮',
    nameEn: 'Warm Drink on the Coast',
    desc: '夜海咖啡馆里，他捧着热饮望向你',
    descEn: 'In the seaside café at night, he holds a hot drink and looks your way',
    gender: 'male',
    image: '/backgrounds/deepseek/mq04.webp',
    desktopImage: '/backgrounds/deepseek/desktop/mq04.jpg',
    thumbnail: '/backgrounds/deepseek/thumbnails/mq04.webp',
    scrim: '#071226',
    brightness: 1,
    saturation: 1,
    mobilePosition: '67% 50%',
    desktopPosition: '50% 60%',
  },
  {
    id: 'deepseek-mq05',
    name: '星台观测',
    nameEn: 'Observatory of Stars',
    desc: '他在星空天文台，替你守着一颗星',
    descEn: 'In the star observatory, he keeps a star for you',
    gender: 'male',
    image: '/backgrounds/deepseek/mq05.webp',
    desktopImage: '/backgrounds/deepseek/desktop/mq05.jpg',
    thumbnail: '/backgrounds/deepseek/thumbnails/mq05.webp',
    scrim: '#061024',
    brightness: 1,
    saturation: 1,
    mobilePosition: '34% 50%',
    desktopPosition: '50% 62%',
  },
  {
    id: 'deepseek-mq06',
    name: '花房来信',
    nameEn: 'Letter from the Greenhouse',
    desc: '玻璃花房里，他拆开一封写给你的信',
    descEn: 'In the glass greenhouse, he opens a letter written for you',
    gender: 'male',
    image: '/backgrounds/deepseek/mq06.webp',
    desktopImage: '/backgrounds/deepseek/desktop/mq06.jpg',
    thumbnail: '/backgrounds/deepseek/thumbnails/mq06.webp',
    scrim: '#071126',
    brightness: 1,
    saturation: 1,
    mobilePosition: '66% 50%',
    desktopPosition: '50% 60%',
  },
  {
    id: 'deepseek-mq07',
    name: '鲸光书房',
    nameEn: 'Study of Whale-Light',
    desc: '他在木质书房，捧着发光鲸鱼陪你',
    descEn: 'In his wooden study he holds a glowing whale and stays with you',
    gender: 'male',
    image: '/backgrounds/deepseek/mq07.webp',
    desktopImage: '/backgrounds/deepseek/desktop/mq07.jpg',
    thumbnail: '/backgrounds/deepseek/thumbnails/mq07.webp',
    scrim: '#061023',
    brightness: 1,
    saturation: 1,
    mobilePosition: '34% 50%',
    desktopPosition: '50% 62%',
  },
  {
    id: 'deepseek-mq08',
    name: '雪岭守候',
    nameEn: 'Waiting by the Snow Ridge',
    desc: '雪夜木屋外，他在湖光里等你',
    descEn: 'Outside the snowbound cabin, he waits for you in the lake light',
    gender: 'male',
    image: '/backgrounds/deepseek/mq08.webp',
    desktopImage: '/backgrounds/deepseek/desktop/mq08.jpg',
    thumbnail: '/backgrounds/deepseek/thumbnails/mq08.webp',
    scrim: '#061025',
    brightness: 1,
    saturation: 1,
    mobilePosition: '66% 50%',
    desktopPosition: '50% 60%',
  },
  {
    id: 'deepseek-mn01',
    name: '蓝时温室',
    nameEn: 'Blue Hour Greenhouse',
    desc: '他站在海边温室的蓝色暮光里',
    descEn: 'He stands in the blue dusk of a seaside greenhouse',
    gender: 'male',
    image: '/backgrounds/deepseek/mn01.webp',
    desktopImage: '/backgrounds/deepseek/desktop/mn01.jpg',
    thumbnail: '/backgrounds/deepseek/thumbnails/mn01.webp',
    scrim: '#081225',
    brightness: 1,
    saturation: 1,
    mobilePosition: '64% 50%',
    desktopPosition: '50% 29%',
  },
  {
    id: 'deepseek-mn02',
    name: '海湾夜茶',
    nameEn: 'Night Tea on the Bay',
    desc: '海湾夜色里，他捧着热饮陪你坐一会儿',
    descEn: 'In the bay at night he sits a while beside you, a hot drink in hand',
    gender: 'male',
    image: '/backgrounds/deepseek/mn02.webp',
    desktopImage: '/backgrounds/deepseek/desktop/mn02.jpg',
    thumbnail: '/backgrounds/deepseek/thumbnails/mn02.webp',
    scrim: '#071126',
    brightness: 1,
    saturation: 1,
    mobilePosition: '35% 50%',
    desktopPosition: '50% 35%',
  },
  {
    id: 'deepseek-mn03',
    name: '城塔折舟',
    nameEn: 'Paper Boat on the Old Town Roof',
    desc: '他在旧城屋顶，为你折起一只纸船',
    descEn: 'On the old town rooftop he folds a paper boat for you',
    gender: 'male',
    image: '/backgrounds/deepseek/mn03.webp',
    desktopImage: '/backgrounds/deepseek/desktop/mn03.jpg',
    thumbnail: '/backgrounds/deepseek/thumbnails/mn03.webp',
    scrim: '#061025',
    brightness: 1,
    saturation: 1,
    mobilePosition: '65% 50%',
    desktopPosition: '50% 35%',
  },
  {
    id: 'deepseek-mn04',
    name: '夜港守望',
    nameEn: 'Watching Over the Night Harbor',
    desc: '夜港灯塔旁，他回眸等你靠近',
    descEn: 'By the lighthouse in the night harbor he looks back, waiting for you to come closer',
    gender: 'male',
    image: '/backgrounds/deepseek/mn04.webp',
    desktopImage: '/backgrounds/deepseek/desktop/mn04.jpg',
    thumbnail: '/backgrounds/deepseek/thumbnails/mn04.webp',
    scrim: '#061025',
    brightness: 1,
    saturation: 1,
    mobilePosition: '66% 50%',
    desktopPosition: '50% 36%',
  },
  {
    id: 'deepseek-mn05',
    name: '海台微光',
    nameEn: 'Faint Light on the Sea Terrace',
    desc: '海岸露台上，他低头看着送你的挂饰',
    descEn: 'On the seaside terrace he looks down at the charm he means to give you',
    gender: 'male',
    image: '/backgrounds/deepseek/mn05.webp',
    desktopImage: '/backgrounds/deepseek/desktop/mn05.jpg',
    thumbnail: '/backgrounds/deepseek/thumbnails/mn05.webp',
    scrim: '#071126',
    brightness: 1,
    saturation: 1,
    mobilePosition: '34% 50%',
    desktopPosition: '50% 28%',
  },
  {
    id: 'deepseek-mn06',
    name: '晨海栈道',
    nameEn: 'Boardwalk at Dawn',
    desc: '晨光落上海边栈道，他陪你等日出',
    descEn: 'Morning light on the seaside boardwalk, where he waits out the sunrise with you',
    gender: 'male',
    image: '/backgrounds/deepseek/mn06.webp',
    desktopImage: '/backgrounds/deepseek/desktop/mn06.jpg',
    thumbnail: '/backgrounds/deepseek/thumbnails/mn06.webp',
    scrim: '#071126',
    brightness: 1,
    saturation: 1,
    mobilePosition: '66% 50%',
    desktopPosition: '50% 29%',
  },
  {
    id: 'deepseek-mn07',
    name: '海崖温室',
    nameEn: 'Cliffside Greenhouse',
    desc: '他站在海崖温室外，陪你望向灯塔',
    descEn: 'Outside the cliffside greenhouse he looks toward the lighthouse with you',
    gender: 'male',
    image: '/backgrounds/deepseek/mn07.webp',
    desktopImage: '/backgrounds/deepseek/desktop/mn07.jpg',
    thumbnail: '/backgrounds/deepseek/thumbnails/mn07.webp',
    scrim: '#071126',
    brightness: 1,
    saturation: 1,
    mobilePosition: '34% 50%',
    desktopPosition: '50% 26%',
  },
  {
    id: 'deepseek-mn08',
    name: '暖灯夜读',
    nameEn: 'Night Reading by the Warm Lamp',
    desc: '暖灯落在书页上，他侧身看向你',
    descEn: 'Warm lamplight on the page, and he turns to look at you',
    gender: 'male',
    image: '/backgrounds/deepseek/mn08.webp',
    desktopImage: '/backgrounds/deepseek/desktop/mn08.jpg',
    thumbnail: '/backgrounds/deepseek/thumbnails/mn08.webp',
    scrim: '#081124',
    brightness: 1,
    saturation: 1,
    mobilePosition: '66% 50%',
    desktopPosition: '50% 22%',
  },
  {
    id: 'deepseek-mn09',
    name: '花房暮海',
    nameEn: 'Dusk Sea Beyond the Flower Room',
    desc: '暮色落进花房，他替你整理一束花',
    descEn: 'Dusk falls into the flower room, and he gathers a bouquet for you',
    gender: 'male',
    image: '/backgrounds/deepseek/mn09.webp',
    desktopImage: '/backgrounds/deepseek/desktop/mn09.jpg',
    thumbnail: '/backgrounds/deepseek/thumbnails/mn09.webp',
    scrim: '#081326',
    brightness: 1,
    saturation: 1,
    mobilePosition: '35% 50%',
    desktopPosition: '50% 35%',
  },
  {
    id: 'deepseek-mn10',
    name: '星港仰望',
    nameEn: 'Looking Up in the Star Port',
    desc: '他在星空港城仰望一场流星',
    descEn: 'In the star port city he looks up at a meteor shower',
    gender: 'male',
    image: '/backgrounds/deepseek/mn10.webp',
    desktopImage: '/backgrounds/deepseek/desktop/mn10.jpg',
    thumbnail: '/backgrounds/deepseek/thumbnails/mn10.webp',
    scrim: '#061023',
    brightness: 1,
    saturation: 1,
    mobilePosition: '35% 50%',
    desktopPosition: '50% 25%',
  },
  {
    id: 'deepseek-mn11',
    name: '雨窗暖饮',
    nameEn: 'Warm Drink at the Rainy Window',
    desc: '雨落城窗，他捧着热饮回头看你',
    descEn: 'Rain on the city window; he turns back to look at you, hot drink in hand',
    gender: 'male',
    image: '/backgrounds/deepseek/mn11.webp',
    desktopImage: '/backgrounds/deepseek/desktop/mn11.jpg',
    thumbnail: '/backgrounds/deepseek/thumbnails/mn11.webp',
    scrim: '#071024',
    brightness: 1,
    saturation: 1,
    mobilePosition: '66% 50%',
    desktopPosition: '50% 36%',
  },
  {
    id: 'deepseek-mn12',
    name: '月海观测',
    nameEn: 'Lunar Sea Observatory',
    desc: '他在月海观测站，为你守着远方',
    descEn: 'At the lunar sea station he keeps watch on the far distance for you',
    gender: 'male',
    image: '/backgrounds/deepseek/mn12.webp',
    desktopImage: '/backgrounds/deepseek/desktop/mn12.jpg',
    thumbnail: '/backgrounds/deepseek/thumbnails/mn12.webp',
    scrim: '#061025',
    brightness: 1,
    saturation: 1,
    mobilePosition: '66% 50%',
    desktopPosition: '50% 48%',
  },
];

/** 按 id 取皮肤；'default'/null/未知 id 均返回 undefined（即无背景） */
export function getChatTheme(id: string | null | undefined): ChatTheme | undefined {
  if (!id || id === DEFAULT_CHAT_THEME_ID) return undefined;
  return CHAT_THEMES.find((t) => t.id === id);
}

/** 按伴侣性别过滤可选皮肤池 */
export function getChatThemesForGender(gender: 'male' | 'female'): ChatTheme[] {
  return CHAT_THEMES.filter((t) => t.gender === gender);
}

/* ==================== UI 色调（界面配色方案） ==================== */

/**
 * UI 色调：聊天界面的整体配色，与背景皮肤解耦，可自由叠加。
 * 每个色调含 dark / light 两种模式；CSS 变量定义在 globals.css
 * 的 html[data-ui-theme='<id>'] 作用域块中（specificity 高于 .dark，可覆盖全局暗色）。
 *
 * scrim：叠加在背景图上的遮罩基调色。深色 UI 用极深夜色，浅色 UI 用奶白色，
 * 保证「界面色调」与「背景图」融合统一。
 */
export interface UiTheme {
  id: string;
  name: string;
  /** 英文名（诗意重命名，用户 2026-10-03 选定）；与中文 `name` 并存，中文态不变。 */
  nameEn: string;
  mode: 'dark' | 'light';
  /** 面板预览底色 */
  swatch: string;
  /** 面板预览点缀色 */
  accent: string;
  /** 背景图遮罩基调色（深色 UI = 深夜色，浅色 UI = 奶白色） */
  scrim: string;
}

/** 默认 UI 色调（= 全局 .dark 变量，无需在 globals.css 中重复定义） */
export const DEFAULT_UI_THEME_ID = 'rose-night';

export const UI_THEMES: UiTheme[] = [
  { id: 'rose-night', name: '墨夜玫瑰', mode: 'dark', swatch: '#1b1518', accent: '#c9757f', scrim: '#151014', nameEn: 'Ink Rose Night' },
  { id: 'rose-milk', name: '奶雾玫瑰', mode: 'light', swatch: '#faf5f5', accent: '#c9757f', scrim: '#f6f0f0', nameEn: 'Milk-Mist Rose' },
  { id: 'amber-night', name: '焦糖夜话', mode: 'dark', swatch: '#1a1510', accent: '#d9a05b', scrim: '#161210', nameEn: 'Caramel Night' },
  { id: 'amber-milk', name: '奶油杏子', mode: 'light', swatch: '#faf5ec', accent: '#d9a05b', scrim: '#f7f2e9', nameEn: 'Cream Apricot' },
  { id: 'mist-night', name: '雾蓝深夜', mode: 'dark', swatch: '#14181d', accent: '#7d9db5', scrim: '#121519', nameEn: 'Mist Blue Midnight' },
  { id: 'mist-milk', name: '晨雾微光', mode: 'light', swatch: '#f2f5f8', accent: '#7d9db5', scrim: '#f1f4f7', nameEn: 'Morning Mist Glow' },
  { id: 'sage-night', name: '松间月色', mode: 'dark', swatch: '#151a14', accent: '#97ad8b', scrim: '#131712', nameEn: 'Moon Through Pines' },
  { id: 'sage-milk', name: '雨后青提', mode: 'light', swatch: '#f4f7f0', accent: '#97ad8b', scrim: '#f3f6ee', nameEn: 'Green Grape After Rain' },
];

/** 按 id 取 UI 色调；null/未知 id 均回退默认 */
export function getUiTheme(id: string | null | undefined): UiTheme {
  return UI_THEMES.find((t) => t.id === id) ?? UI_THEMES[0];
}

/** 校验 id 是否为合法 UI 色调 */
export function isUiThemeId(id: string): boolean {
  return UI_THEMES.some((t) => t.id === id);
}
