import {test,expect} from '@playwright/test';
import {profile,resetFixture,customize,meet,openSettings,json,chooseLocale,fixtureDb} from './helpers/personal';
test.setTimeout(90_000);
test('Gemini-only compatibility is explained in both languages without autoplay',async({page,request})=>{
 test.skip(profile!=='gemini','Run E2E_PROFILE=gemini');resetFixture();await customize(page,'en');await meet(page,'en');await json(request,'/api/e2e/trace','POST',{});await openSettings(page,'en');await expect(page.getByTestId('speech-compatibility-notice')).toBeVisible();await expect(page.getByTestId('speech-compatibility-notice')).toContainText(/code|compatible/i);await expect(page.getByTestId('speech-voice-settings').getByRole('combobox').locator('option')).toHaveCount(13);await page.keyboard.press('Escape');await chooseLocale(page,'zh-CN');await openSettings(page,'zh-CN');await expect(page.getByTestId('speech-compatibility-notice')).toContainText(/代号|兼容/);expect((await json(request,'/api/e2e/trace')).speechCalls).toHaveLength(0);expect((await json(request,'/api/capabilities')).speechPresentation.mode).toBe('compatibility');
});
test('password owner login, hostile requests and forged visitor headers',async({page,request,playwright})=>{
 test.skip(profile!=='password','Run E2E_PROFILE=password');resetFixture();const base=process.env.E2E_BASE_URL!;
 expect((await request.get('/api/visitor')).status()).toBe(401);await page.goto('/chat');await expect(page.getByTestId('owner-login')).toBeVisible();await page.getByTestId('owner-password').fill('incorrect');await page.getByTestId('owner-sign-in').click();await expect(page.getByRole('alert')).toBeVisible();await page.getByTestId('owner-password').fill('synthetic-owner-password-2026');await page.getByTestId('owner-sign-in').click();await expect(page.getByTestId('owner-login')).not.toBeVisible();
 const owner=(await json(page.request,'/api/visitor')).visitor_id;const cookies=await page.context().cookies();expect(cookies.find(c=>c.name==='dw_owner')).toMatchObject({httpOnly:true,sameSite:'Strict'});await customize(page,'en');await meet(page,'en');const conv=(await json(page.request,'/api/conversations')).conversations[0];const messages=(await json(page.request,`/api/conversations/${conv.id}/messages`)).messages;const assistant=messages.find((m:{role:string})=>m.role==='assistant');const tts=await json(page.request,'/api/tts','POST',{message_id:assistant.id});const unauth=await playwright.request.newContext({baseURL:base});try{expect((await unauth.get(tts.audio_url)).status()).toBe(401)}finally{await unauth.dispose()}
 const raw=await page.request.get('/api/visitor',{headers:{'X-Visitor-Id':'a-different-forged-owner','x-session':'fake-token'}});expect((await raw.json()).visitor_id).toBe(owner);
 const cross=await page.request.patch('/api/visitor',{headers:{Origin:'https://evil.invalid'},data:{palette:'blue'}});expect(cross.status()).toBe(403);const noOrigin=await page.request.patch('/api/visitor',{data:{palette:'blue'}});expect(noOrigin.status()).toBe(403);const site=await page.request.get('/api/visitor',{headers:{'Sec-Fetch-Site':'cross-site'}});expect(site.status()).toBe(403);const hostileHost=await page.request.get('/api/visitor',{headers:{Host:'evil.invalid'}});expect(hostileHost.status()).toBe(403);
 await json(page.request,'/api/owner/session','DELETE');expect((await page.request.get('/api/visitor')).status()).toBe(401);await page.reload();await expect(page.getByTestId('owner-login')).toBeVisible();const db=fixtureDb();try{expect((db.prepare('SELECT count(*) n FROM visitors').get() as {n:number}).n).toBe(1)}finally{db.close()}
});
test('missing browser timezone falls back and saved timezone survives a second browser',async({page,browser})=>{
 test.skip(profile==='password'||profile==='gemini','Local catalog profiles');resetFixture();await page.addInitScript(()=>{const original=Intl.DateTimeFormat.prototype.resolvedOptions;Intl.DateTimeFormat.prototype.resolvedOptions=function(){return {...original.call(this),timeZone:'Invalid/Zone'}}});await customize(page,'en');await expect(page.getByTestId('onboarding-timezone')).toHaveValue('Asia/Shanghai');await page.getByTestId('onboarding-timezone').fill('America/New_York');await meet(page,'en');const context=await browser.newContext({timezoneId:'Pacific/Auckland'});try{const other=await context.newPage();await customize(other,'en',{repick:true,index:2});await expect(other.getByTestId('onboarding-timezone')).toHaveCount(0);await meet(other,'en');expect((await json(other.request,'/api/profile')).profile.timezone).toBe('America/New_York')}finally{await context.close()}
});
test('signed unsubscribe browser GET stays inert and form POST stops email only',async({page,request})=>{
 test.skip(profile==='password'||profile==='gemini','Local catalog profiles');resetFixture();await json(request,'/api/letters/preferences','PATCH',{in_app_enabled:true,email_address:'synthetic@example.invalid',email_enabled:true});
 const {createHmac}=await import('node:crypto');const {readFileSync}=await import('node:fs');const {default:path}=await import('node:path');const owner=(await json(request,'/api/visitor')).visitor_id;const secret=readFileSync(path.join(process.env.E2E_DATA_DIR!,'private/unsubscribe.key'),'utf8').trim();const body=Buffer.from(JSON.stringify({owner,expiresAt:Date.now()+60000})).toString('base64url');const token=body+'.'+createHmac('sha256',secret).update(body).digest('base64url');await page.goto(`/api/letters/unsubscribe?token=${encodeURIComponent(token)}`);expect((await json(request,'/api/letters/preferences')).preference.email_enabled).toBe(true);const posted=page.waitForRequest(r=>r.method()==='POST'&&r.url().includes('/api/letters/unsubscribe'));await page.getByRole('button').click();const headers=await (await posted).allHeaders();expect(headers.origin).toBe(process.env.E2E_BASE_URL);expect(headers.referer).toBe(process.env.E2E_BASE_URL+'/');expect(headers.referer).not.toContain('token');await expect.poll(async()=>(await json(request,'/api/letters/preferences')).preference.email_enabled).toBe(false);const after=(await json(request,'/api/letters/preferences')).preference;expect(after.in_app_enabled).toBe(true);expect(after.email_status).toBe('unsubscribed');expect((await request.get(`/api/letters/unsubscribe?token=${token}forged`)).status()).toBe(400);for(const origin of ['null','https://evil.invalid'])expect((await request.post(`/api/letters/unsubscribe?token=${token}`,{headers:{Origin:origin}})).status()).toBe(403);
});
test('rose and blue chat palette choices persist and render in the real viewport',async({page,request},info)=>{
 test.skip(profile!=='keyword','One dedicated visual matrix');resetFixture();await customize(page,'en');await meet(page,'en');for(const value of ['rose','blue']){const toggle=page.getByTestId('palette-toggle');if(await toggle.getAttribute('data-palette-value')!==value)await toggle.click();await expect(toggle).toHaveAttribute('data-palette-value',value);await toggle.click();await expect.poll(async()=>(await json(request,'/api/visitor')).visitor.palette).toBe(value);await expect(page.getByTestId('active-companion-header')).toHaveAttribute('data-surface',new RegExp('^dream-'+value));await expect(page.getByTestId('message-textarea')).toBeVisible();await page.screenshot({path:info.outputPath(`${value}-${info.project.name}.png`),fullPage:true})}await page.reload();await expect(page.getByTestId('active-companion-header')).toHaveAttribute('data-surface',/^dream-blue/);expect((await json(request,'/api/visitor')).visitor.palette).toBe('blue');
});
