import {test,expect} from '@playwright/test';
import {createHash} from 'node:crypto';
import {customize,meet,send,choosePalette,openSettings,json,resetFixture,fixtureDb,hitTest,profile} from './helpers/personal';
const PNG=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Y9ZQmcAAAAASUVORK5CYII=','base64');
test.describe('personal real browser journeys',()=>{
 test.skip(profile==='password'||profile==='gemini','Dedicated security/compatibility profile');test.setTimeout(150_000);
 for(const locale of ['zh-CN','en'] as const){test(`${locale}: onboard, calendar, SSE, media, settings and two companions`,async({page,request},testInfo)=>{
  resetFixture();await json(request,'/api/e2e/trace','POST',{});await page.context().addInitScript(()=>{localStorage.clear()});
  await customize(page,locale);await choosePalette(page,locale==='en'?'blue':'rose');
  const tz=page.getByTestId('onboarding-timezone');await expect(tz).toHaveValue(/.+/);await tz.fill('Not/AZone');await expect(tz).toHaveAttribute('aria-invalid','true');await expect(page.getByRole('button',{name:locale==='en'?'Meet them':'遇见 TA',exact:true})).toBeDisabled();await tz.fill('Europe/Paris');
  await page.getByTestId('companion-my-birthday').getByRole('button').click();const prev=page.getByRole('button',{name:locale==='en'?'Previous year':'上一年',exact:true});const next=page.getByRole('button',{name:locale==='en'?'Next year':'下一年',exact:true});const year=page.getByRole('combobox',{name:locale==='en'?'Year':'年份',exact:true});await hitTest(prev);await hitTest(next);await hitTest(year);const before=Number(await year.inputValue());await prev.click();await expect(year).toHaveValue(String(before-1));await next.click();await expect(year).toHaveValue(String(before));await year.selectOption('1900');await expect(prev).toBeDisabled();await year.selectOption(String(new Date().getFullYear()+10));await expect(next).toBeDisabled();await year.selectOption('1995');await page.locator('button[data-day]').filter({hasText:/^15$/}).first().click();await expect(page.getByTestId('companion-my-birthday').getByRole('button')).toContainText('1995');
  await page.getByRole('button',{name:locale==='en'?'Enhance':'一键完善',exact:true}).click();await expect(page.getByTestId('persona-enhancement-preview')).toBeVisible();await page.getByTestId('persona-enhancement-preview').getByRole('button').first().click();
  await meet(page,locale);expect((await json(request,'/api/e2e/trace')).speechCalls).toHaveLength(0);const first=(await json(request,'/api/conversations')).conversations[0];const firstCompanion=first.companion_id;
  const p=(await json(request,'/api/profile')).profile;expect(p.timezone).toBe('Europe/Paris');expect(p.birthday).toMatch(/^1995-/);
  await json(request,'/api/e2e/trace','POST',{});await send(page,'[E2E_MEMORY_FACT:喜欢薄荷茶] 我喜欢薄荷茶。',locale);const messages=(await json(request,`/api/conversations/${first.id}/messages`)).messages;const assistant=messages.filter((m:{role:string})=>m.role==='assistant').at(-1);const bubble=page.getByTestId(`message-${assistant.id}`);
  await expect.poll(async()=>{const db=fixtureDb();try{return db.prepare('SELECT count(*) AS n FROM memories WHERE companion_id=?').get(firstCompanion) as {n:number}}finally{db.close()}},{timeout:20_000}).toMatchObject({n:1});
  if(profile==='hybrid')await expect.poll(()=>{const db=fixtureDb();try{return (db.prepare('SELECT count(*) n FROM memories WHERE companion_id=? AND embedding IS NOT NULL AND embedding_dimensions=1024').get(firstCompanion) as {n:number}).n}finally{db.close()}},{timeout:20_000}).toBe(1);expect((await json(request,'/api/e2e/trace')).speechCalls).toHaveLength(0);
  await bubble.getByTestId('feedback-up').click();await bubble.getByTestId('feedback-comment-area').fill('synthetic E2E useful reply');await bubble.getByTestId('feedback-save-comment').click();await expect.poll(async()=>(await json(request,`/api/feedback?conversation_id=${first.id}`)).feedback).toEqual(expect.arrayContaining([expect.objectContaining({rating:1,comment:'synthetic E2E useful reply'})]));
  await page.evaluate(()=>{const original=HTMLMediaElement.prototype.play;const target=window as unknown as {e2eAudio:{played:number;ended:number}};target.e2eAudio={played:0,ended:0};HTMLMediaElement.prototype.play=function(){target.e2eAudio.played++;this.addEventListener('ended',()=>target.e2eAudio.ended++,{once:true});return original.call(this)}});
  await bubble.getByTestId('voice-bar').click();await expect.poll(()=>page.evaluate(()=>(window as unknown as {e2eAudio:{ended:number}}).e2eAudio.ended)).toBe(1);expect((await json(request,'/api/e2e/trace')).speechCalls).toHaveLength(1);await bubble.getByTestId('voice-bar').click();await expect.poll(()=>page.evaluate(()=>(window as unknown as {e2eAudio:{ended:number}}).e2eAudio.ended)).toBe(2);expect((await json(request,'/api/e2e/trace')).speechCalls).toHaveLength(1);
  await openSettings(page,locale);const dialog=page.getByTestId('companion-settings');await dialog.getByTestId('speech-voice-settings').getByRole('combobox').selectOption('voice-zh-f-02');await dialog.getByRole('button',{name:locale==='en'?'Save':'保存',exact:true}).last().click();await expect(dialog).not.toBeVisible();await expect(bubble.getByTestId('voice-stale-notice')).toBeVisible();await bubble.getByTestId('voice-regenerate').click();await expect.poll(async()=>(await json(request,'/api/e2e/trace')).speechCalls.length).toBe(2);await expect(bubble.getByTestId('voice-stale-notice')).not.toBeVisible();
  await page.locator('input[type=file]').setInputFiles({name:'synthetic.png',mimeType:'image/png',buffer:PNG});await send(page,'这张图片是一朵花。',locale);expect((await json(request,`/api/conversations/${first.id}/messages`)).messages.some((m:{role:string;image_url:string})=>m.role==='user'&&m.image_url)).toBe(true);
  const photoFrames=await send(page,'给我发一张照片',locale);expect(photoFrames).not.toContain('[PHOTO:');await expect.poll(async()=>(await json(request,'/api/e2e/trace')).imageCalls.length).toBe(1);await expect.poll(async()=>(await json(request,`/api/conversations/${first.id}/messages`)).messages.filter((m:{role:string;content_type:string})=>m.role==='assistant'&&m.content_type==='image').length).toBe(1);const photo=(await json(request,`/api/conversations/${first.id}/messages`)).messages.find((m:{role:string;content_type:string})=>m.role==='assistant'&&m.content_type==='image');const imageTrace=(await json(request,'/api/e2e/trace')).imageCalls[0];const reference=await request.get(`/characters/deepseek/${first.companion_character_key}-chibi.png`);expect(imageTrace.referenceSha256).toEqual([createHash('sha256').update(await reference.body()).digest('hex')]);const stale=await request.post('/api/photo',{headers:{Origin:process.env.E2E_BASE_URL!},data:{conversation_id:first.id,appearance_style:'normal',photo_scene:'a park'}});expect(stale.status()).toBe(409);const media=await request.get(photo.image_url);expect(media.status()).toBe(200);expect(media.headers()['content-type']).toMatch(/^image\/png/);expect(media.headers()['x-content-type-options']).toBe('nosniff');const ranged=await request.get(photo.image_url,{headers:{Range:'bytes=0-7'}});expect(ranged.status()).toBe(206);expect((await ranged.body()).length).toBe(8);
  await send(page,'你还记得我喜欢薄荷茶吗？',locale);const trace=await json(request,'/api/e2e/trace');expect(trace.chatSystemPrompts.at(-1)).toContain('喜欢薄荷茶');if(profile==='hybrid')expect(trace.embeddingCalls.length).toBeGreaterThan(0);
  await json(request,'/api/profile','PUT',{feedback_action:'append',feedback:'Please listen patiently'});await openSettings(page,locale);const settings=page.getByTestId('companion-settings');const preferences=settings.getByTestId('companion-preference-settings');await expect(preferences).toContainText('Please listen patiently');await preferences.getByRole('button',{name:locale==='en'?'Edit':'更正',exact:true}).first().click();await preferences.getByRole('textbox').fill('Please be concise and patient');await preferences.getByRole('button',{name:locale==='en'?'Save':'保存',exact:true}).click();await expect.poll(async()=>(await json(request,'/api/profile')).profile.communication_prefs.explicit_feedback).toContain('Please be concise and patient');const letters=settings.getByTestId('companion-letter-settings');await expect(letters.getByRole('switch').first()).toBeEnabled();await letters.getByRole('switch').first().click();await expect.poll(async()=>(await json(request,'/api/letters/preferences')).preference.in_app_enabled).toBe(true);await expect(letters.locator('#letter-email-copy')).toBeDisabled();await expect(letters.getByTestId('letter-inbox')).toBeVisible();await page.keyboard.press('Escape');const current=(await json(request,'/api/profile')).profile;const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Paris'}).format(new Date());await json(request,'/api/profile','PUT',{important_dates:[{date:today,type:'anniversary',description:'E2E special day',recurring:false}],profile_updated_at:current.updated_at});await expect.poll(async()=>(await json(request,'/api/letters')).letters.length,{timeout:20_000}).toBe(1);await openSettings(page,locale);const inbox=page.getByTestId('letter-inbox');await inbox.getByRole('button').click();await expect(inbox).toContainText('I am thinking of you today');await expect.poll(async()=>(await json(request,'/api/letters')).letters[0].read_at).not.toBeNull();await page.keyboard.press('Escape');
  await page.getByTestId('active-companion-header').getByRole('button',{name:locale==='en'?'Chat appearance':'聊天装扮',exact:true}).click();const theme=page.getByTestId('theme-settings');await expect(theme).toHaveAttribute('data-companion-id',firstCompanion);await theme.getByRole('button').nth(1).click();await expect.poll(async()=>(await json(request,'/api/visitor')).visitor.ui_theme).not.toBeNull();await page.keyboard.press('Escape');
  await customize(page,locale,{repick:true,index:1});await expect(page.getByTestId('onboarding-timezone')).toHaveCount(0);await meet(page,locale);const second=(await json(request,'/api/conversations')).conversations.find((c:{id:string})=>c.id!==first.id);expect(second.companion_id).not.toBe(firstCompanion);expect((await json(request,'/api/profile')).profile.timezone).toBe('Europe/Paris');await expect(page.getByTestId('active-companion-header')).toHaveAttribute('data-companion-id',second.companion_id);await send(page,'[E2E_MEMORY_FACT:喜欢蓝莓] 我喜欢蓝莓。',locale);await expect.poll(()=>{const db=fixtureDb();try{return (db.prepare('SELECT count(*) AS n FROM memories WHERE companion_id=?').get(second.companion_id) as {n:number}).n}finally{db.close()}},{timeout:20_000}).toBe(1);
  const deletion=await json(request,`/api/conversations/${first.id}`,'DELETE');expect(deletion.ok).toBe(true);expect(deletion.forget.status).toBe('cleared');const db=fixtureDb();try{expect((db.prepare('SELECT count(*) AS n FROM memories WHERE companion_id=?').get(firstCompanion) as {n:number}).n).toBe(0);expect((db.prepare('SELECT count(*) AS n FROM memories WHERE companion_id=?').get(second.companion_id) as {n:number}).n).toBe(1);expect(db.prepare('SELECT payload FROM memory_recall_snapshots WHERE companion_id=?').get(firstCompanion)).toBeUndefined()}finally{db.close()}
  await page.reload();await expect(page.getByTestId('active-companion-header')).toHaveAttribute('data-companion-id',second.companion_id);await page.screenshot({path:testInfo.outputPath(`${locale}-${testInfo.project.name}.png`),fullPage:true});
 });}
});
