import {test,expect} from '@playwright/test';
import {spawn,type ChildProcess} from 'node:child_process';
import {mkdtempSync,readFileSync,existsSync,rmSync} from 'node:fs';
import os from 'node:os';import path from 'node:path';import {createRequire} from 'node:module';
import Database from 'better-sqlite3';
import {readOwnedE2EInventory,stopOwnedE2EApp,type E2EHolder} from '../scripts/personal/e2e-cleanup';
import {profile} from './helpers/personal';
const candidate=process.env.E2E_CANDIDATE_DIR||process.cwd();
const require=createRequire(path.join(candidate,'package.json'));
const sleep=(ms:number)=>new Promise(resolve=>setTimeout(resolve,ms));
function alive(pid:number){try{process.kill(pid,0);return true}catch{return false}}
async function exit(child:ChildProcess,timeout=10_000){if(child.exitCode!==null||child.signalCode!==null)return;await Promise.race([new Promise(resolve=>child.once('exit',resolve)),sleep(timeout)]);if(child.exitCode===null&&child.signalCode===null)throw new Error('Child did not exit');}
async function cli(args:string[],env:NodeJS.ProcessEnv){const child=spawn(process.execPath,[require.resolve('tsx/cli'),...args],{cwd:candidate,env,stdio:['ignore','pipe','pipe']});let output='';child.stdout!.on('data',d=>output+=d);child.stderr!.on('data',d=>output+=d);await exit(child,30_000);return {code:child.exitCode,output};}
test('clean exported production package: persist, drain backup, restore, child failure',async({playwright},testInfo)=>{
 test.skip(!process.env.E2E_CANDIDATE_DIR||profile!=='keyword'||testInfo.project.name!=='chromium','One lifecycle run against separate exported production package');test.setTimeout(120_000);
 const data=mkdtempSync(path.join(os.tmpdir(),'dw-e2e-lifecycle-'));const restored=`${data}-restored`;const base='http://127.0.0.1:5518';
 const env={...process.env,APP_ENV:'test',E2E_MOCK_PROVIDERS:'1',APP_DATA_DIR:data,APP_ACCESS_MODE:'local',OWNER_PASSWORD:'',HOST:'127.0.0.1',PORT:'5518',APP_BASE_URL:base,MEMORY_RETRIEVAL_MODE:'keyword',EMAIL_PROVIDER:'none',LETTER_DELIVERY:'in-app',OBJECT_STORAGE_PROVIDER:'local',AI_TTS_PROVIDER:'',AI_TTS_MODEL:''};for(const key of ['DEEPSEEK_API_KEY','OPENROUTER_API_KEY','DASHSCOPE_API_KEY','RESEND_API_KEY','SMTP_PASSWORD','R2_ACCESS_KEY_ID','R2_SECRET_ACCESS_KEY'])Reflect.set(env,key,'');
 const request=await playwright.request.newContext({baseURL:base,extraHTTPHeaders:{Origin:base}});let app:ChildProcess|undefined;let logs='';let passed=false;let cleanupConfirmed=false;let holder:E2EHolder|undefined;
 const start=async(dir:string)=>{Reflect.set(env,'APP_DATA_DIR',dir);cleanupConfirmed=false;holder=undefined;app=spawn(process.execPath,[require.resolve('tsx/cli'),'scripts/personal/start.ts','start'],{cwd:candidate,env,stdio:['ignore','pipe','pipe']});app.stdout!.on('data',d=>logs+=d);app.stderr!.on('data',d=>logs+=d);const end=Date.now()+30_000;while(Date.now()<end){if(app.exitCode!==null)throw new Error(logs);try{if((await request.get('/api/capabilities')).ok()){holder=readOwnedE2EInventory(dir);return}}catch{}await sleep(100)}throw new Error('Production readiness timeout')};
 const stop=async()=>{if(!app)return;cleanupConfirmed=await stopOwnedE2EApp(env.APP_DATA_DIR!,app,{holder,previouslyStopped:cleanupConfirmed});if(!cleanupConfirmed)throw new Error('Production E2E processes did not stop; retain synthetic data');};
 try{
  Reflect.set(env,'E2E_MOCK_PROVIDERS','0');await start(data);const unavailable=(await (await request.get('/api/capabilities')).json()).capabilities;expect(unavailable.chat.enabled).toBe(false);expect(unavailable.speech.enabled).toBe(false);expect(unavailable.image.enabled).toBe(false);expect((await request.get('/pricing')).status()).toBe(404);const owner=(await (await request.get('/api/visitor')).json()).visitor_id;
  const post=async(url:string,body:unknown)=>{const r=await request.post(url,{data:body});expect(r.status(),await r.text()).toBe(200);return r.json()};
  await post('/api/visitor',{gender:'male',orientation:'female'});const catalog=[];for(const gender of ['f','m'])for(let i=1;i<=4;i++){const key=`deepseek_${gender}_0${i}`;const c=(await post('/api/companions',{character_key:key,name:`E2E${gender}${i}`,appearance_style:i%2?'chibi':'normal'})).companion;catalog.push(c);const asset=await request.get(`/characters/deepseek/${key}-${i%2?'chibi':'normal'}.png`);expect(asset.status()).toBe(200)}expect(catalog).toHaveLength(8);
  const conversation=(await post('/api/conversations',{companion_id:catalog[0].id})).conversation;
  expect((await request.post('/api/chat',{data:{conversation_id:conversation.id,content:'This must not call a provider'}})).status()).toBe(503);expect((await request.post('/api/tts-preview',{data:{voice_id:'voice-zh-f-01'}})).status()).toBe(503);await stop();Reflect.set(env,'E2E_MOCK_PROVIDERS','1');await start(data);await post('/api/e2e/trace',{chatChunkDelayMs:1200});const chat=request.post('/api/chat',{data:{conversation_id:conversation.id,content:'Persist this synthetic production conversation'}});await expect.poll(()=>{const db=new Database(path.join(data,'deep-whisper.sqlite'),{readonly:true});try{return (db.prepare('SELECT count(*) n FROM operation_leases').get() as {n:number}).n}finally{db.close()}}).toBeGreaterThan(0);
  const backup=cli(['scripts/personal/data.ts','backup'],env);await expect.poll(()=>existsSync(path.join(data,'private/maintenance.json'))).toBe(true);const blocked=await request.patch('/api/visitor',{data:{palette:'blue'}});expect(blocked.status()).toBe(503);const streamed=await chat;expect((await streamed.text())).toContain('"type":"done"');const backed=await backup;expect(backed.code,backed.output).toBe(0);const folder=backed.output.trim().split('\n').find(line=>line.startsWith(data+'/backups/'))!;expect(folder).toBeTruthy();const manifest=JSON.parse(readFileSync(path.join(folder,'manifest.json'),'utf8'));expect(manifest.databaseVersion).toBe(3);expect(Object.keys(manifest.files).some(p=>p.includes('instance.json'))).toBe(false);expect((await request.patch('/api/visitor',{data:{palette:'blue'}})).status()).toBe(200);
  await stop();await start(data);expect((await (await request.get('/api/visitor')).json()).visitor_id).toBe(owner);expect((await (await request.get(`/api/conversations/${conversation.id}/messages`)).json()).messages).toHaveLength(2);await stop();const result=await cli(['scripts/personal/data.ts','restore',folder,restored],env);expect(result.code,result.output).toBe(0);await start(restored);expect((await (await request.get('/api/visitor')).json()).visitor_id).toBe(owner);expect((await (await request.get(`/api/conversations/${conversation.id}/messages`)).json()).messages).toHaveLength(2);
  const lock=JSON.parse(readFileSync(path.join(restored,'private/instance.json'),'utf8'));const worker=lock.children.find((c:{role:string})=>c.role==='worker');expect(worker).toBeTruthy();process.kill(worker.pid,'SIGTERM');await exit(app!);await expect.poll(()=>lock.children.filter((c:{pid:number})=>alive(c.pid)).length,{timeout:10_000}).toBe(0);expect(app!.exitCode!==0||app!.signalCode!==null).toBe(true);passed=true;
 }finally{try{await stop()}finally{await request.dispose();await testInfo.attach('production-lifecycle-log',{body:logs,contentType:'text/plain'});if(passed&&cleanupConfirmed){rmSync(data,{recursive:true,force:true});rmSync(restored,{recursive:true,force:true})}else console.log('Lifecycle synthetic fixture retained:',data)}}
});
